In [267]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import json
import numpy as np
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

Mapa de hospitais mais recente que encontrei vem da seguinte deliberação da secretaria de estado da saude de sp:

Deliberação Nº 47 - CIB - 10 de Junho de 2020 
https://ses.sp.bvs.br/leisref/resource/?id=leisref.act.5212

ftp://ftp.saude.sp.gov.br/ftpsessp/bibliote/informe_eletronico/2020/iels.jun.20/Iels105/E_DL-CIB-47_100620.pdf

http://portal.saude.sp.gov.br/resources/ses/perfil/cidadao/homepage-new/outros-destaques/covid-19/delib_cib_planilha_covid_09_04_2020.pdf

In [268]:
df = pd.read_csv('mapa_hospitais_cleaner.csv', sep=';')
# df = df.applymap(lambda x: x.replace('\n',' ') if isinstance(x,str) else x)

In [269]:
df

DRS          DRSNOME                  REGSAUDE               MUNICIPIO  \
0      1  GRANDE S. PAULO             Alto do Tiete                   ARUJA   
1      1  GRANDE S. PAULO             Alto do Tiete                   ARUJA   
2      1  GRANDE S. PAULO             Alto do Tiete          BIRITIBA MIRIM   
3      1  GRANDE S. PAULO             Alto do Tiete  FERRAZ DE\nVASCONCELOS   
4      1  GRANDE S. PAULO             Alto do Tiete   FERRAZ DE VASCONCELOS   
..   ...              ...                       ...                     ...   
622   17          TAUBATÉ  Circ. da Fe-V. Historico                  QUELUZ   
623   17          TAUBATÉ             Litoral Norte         CARAGUATATUB\nA   
624   17          TAUBATÉ             Litoral Norte         CARAGUATATUB\nA   
625   17          TAUBATÉ             Litoral Norte                ILHABELA   
626   17          TAUBATÉ             Litoral Norte           SAO SEBASTIAO   

          CNES  \
0    6451098.0   
1    6628842.0   
2          NaN   
3    2080079.0   
4     116750.0   
..         ...   
622  2058340.0   
623  2082926.0   
624    92894.0   
625  2747871.0   
626  2765934.0   

                                                                   NOME  \
0                                      HOSPITAL DALILA FERREIRA BARBOSA   
1                                            PRONTO ATENDIMENTO BARRETO   
2                                            POSTO DE ATENDIMENTO COVID   
3             HOSPITAL DR OSIRIS FLORINDO\nCOELHO FERRAZ DE VASCONCELOS   
4    HOSPITAL DE CAMPANHA DE FERRAZ/GINASIO PROF. ADÃO DIAS\nDOS SANTOS   
..                                                                  ...   
622                                        HOSPITAL MUNICIPAL DE QUELUZ   
623                                          CASA DE SAUDE STELLA MARIS   
624                                                    HR LITORAL NORTE   
625                              HOSPITAL MUNICIPAL GOV MARIO\nCOVAS JR   
626                              HOSPITAL DE CLINICAS DE SAO\nSEBASTIAO   

    GESTAO       GRUPO_DE_HOSPITAIS  LEITOS_CLIN_ANTERIOR_A_COVID  \
0        M               Municipais                           9.0   
1        M               Municipais                           NaN   
2        M               Municipais                           NaN   
3        E         Estaduais-Direta                          60.0   
4        M               Municipais                          18.0   
..     ...                      ...                           ...   
622      M               Municipais                           8.0   
623      M  Priv.s. fins lucrativos                          50.0   
624      E            Estaduais-OSS                          93.0   
625      M               Municipais                          30.0   
626      M  Priv.s. fins lucrativos                          53.0   

    LEITOS_CLIN_SUS LEITOS_CLIN_EXISTENTE_CONVERTIDO_PARA_COVID  \
0                 9                                           -   
1               NaN                                         NaN   
2               NaN                                         NaN   
3                60                                          16   
4                18                                         NaN   
..              ...                                         ...   
622               8                                           2   
623              40                                          21   
624              93                                           -   
625              30                                           2   
626              47                                          16   

    LEITO_CLINICO_AMPLIADO_EM_FUNCIONAMENTO  \
0                                         -   
1                                       NaN   
2                                       NaN   
3                                         -   
4                                        20   
..                    

In [270]:
df.columns

Index(['DRS', 'DRSNOME', 'REGSAUDE', 'MUNICIPIO', 'CNES', 'NOME', 'GESTAO',
       'GRUPO_DE_HOSPITAIS', 'LEITOS_CLIN_ANTERIOR_A_COVID', 'LEITOS_CLIN_SUS',
       'LEITOS_CLIN_EXISTENTE_CONVERTIDO_PARA_COVID',
       'LEITO_CLINICO_AMPLIADO_EM_FUNCIONAMENTO',
       'LEITO_CLINICO_PARA_AMPLIACAO_FUTURA', 'UTI_ADULTO_EXISTE',
       'UTI_ADULTO_SUS', 'UTI_ADULTO_EXISTENTE_CONVERTIDO_PARA_COVID',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_1',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_2',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_3',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_4',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_5',
       'UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_6'],
      dtype='object')

In [271]:
df['DRS'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [272]:
df['DRSNOME'] = df['DRSNOME'].apply(lambda x: x.replace('\n', ' '))
df['DRSNOME'].unique()

array(['GRANDE S. PAULO', 'ARAÇATUBA', 'ARARAQUARA', 'BAIXADA SANTISTA',
       'BARRETOS', 'BAURU', 'CAMPINAS', 'FRANCA', 'MARÍLIA', 'PIRACICABA',
       'PRESIDENTE PRUDENTE', 'REGISTRO', 'RIBEIRÃO PRETO',
       'S. JOÃO B. VISTA', 'S. JOSÉ R. PRETO', 'SOROCABA', 'TAUBATÉ'],
      dtype=object)

In [273]:
for i in df['REGSAUDE']:
    if '\n' in i: print(i)

In [274]:
df['REGSAUDE'].unique()

array(['Alto do Tiete', 'Franco da Rocha', 'Grande ABC', 'Mananciais',
       'Rota dos Bandeirantes', 'Sao Paulo', 'Central do DRS II',
       'Consorcio do DRS II', 'Lagos do DRS II', 'Central do DRS III',
       'Centro Oeste do DRS III', 'Coracao do DRS III',
       'Norte do DRS III', 'Baixada Santista', 'Norte - Barretos',
       'Sul - Barretos', 'Bauru', 'Jau', 'Lins', 'Polo Cuesta',
       'Vale do Jurumirim', 'Braganca', 'Circuito das aguas', 'Jundiai',
       'Reg. Metrop. Campinas', 'Alta Anhanguera', 'Alta Mogiana',
       'Tres Colinas', 'Adamantina', 'Assis', 'Marilia', 'Ourinhos',
       'Tupa', 'Araras', 'Limeira', 'Piracicaba', 'Rio Claro',
       'Alta Paulista', 'Alta Sorocabana', 'Alto Capivari',
       'Extremo Oeste Paulista', 'Pontal do Paranapanema',
       'Vale do Ribeira', 'Aquifero Guarani', 'Horizonte Verde',
       'Vale das Cachoeiras', 'Baixa Mogiana', 'Mantiqueira', 'Rio Pardo',
       'Catanduva', 'Fernandopolis', 'Jales', 'Jose Bonifacio',
       'Sa

In [275]:
df['MUNICIPIO'].nunique()

333

In [276]:
df['MUNICIPIO'] = df['MUNICIPIO'].apply(lambda x: x.replace('\n', ' ') if x != 'CARAGUATATUB\nA' else 'CARAGUATATUBA')
df['MUNICIPIO'].unique()

array(['ARUJA', 'BIRITIBA MIRIM', 'FERRAZ DE VASCONCELOS', 'GUARAREMA',
       'GUARULHOS', 'ITAQUAQUECETUBA', 'MOGI DAS CRUZES', 'POA',
       'SALESOPOLIS', 'SANTA ISABEL', 'SUZANO', 'CAIEIRAS', 'CAJAMAR',
       'FRANCISCO MORATO', 'FRANCO DA ROCHA', 'MAIRIPORA', 'DIADEMA',
       'MAUA', 'RIBEIRAO PIRES', 'SANTO ANDRE', 'SAO BERNARDO DO CAMPO',
       'SAO CAETANO DO SUL', 'COTIA', 'EMBU', 'ITAPECERICA DA SERRA',
       'TABOAO DA SERRA', 'BARUERI', 'CARAPICUIBA', 'ITAPEVI', 'OSASCO',
       'Osasco', 'SANTANA DE PARNAIBA', 'SAO PAULO', 'SÃO PAULO',
       'ARACATUBA', 'AURIFLAMA', 'BILAC', 'GUARARAPES', 'VALPARAISO',
       'ALTO ALEGRE', 'BIRIGUI', 'BURITAMA', 'CLEMENTINA', 'PENAPOLIS',
       'ANDRADINA', 'CASTILHO', 'GUARACAI', 'ILHA SOLTEIRA',
       'MIRANDOPOLIS', 'PEREIRA BARRETO', 'SUD MENNUCCI',
       'AMERICO BRASILIENSE', 'AMERICO BRASILI', 'ARARAQUARA',
       'BOA ESPERANCA DO SUL', 'BORBOREMA', 'IBITINGA', 'ITAPOLIS',
       'NOVA EUROPA', 'TABATINGA', 'DESCALVADO',

In [277]:
df['GESTAO'].unique()

array(['M', 'E'], dtype=object)

In [278]:
df['GRUPO_DE_HOSPITAIS'].unique()

array(['Municipais', 'Estaduais-Direta', 'Priv.s. fins lucrativos',
       'Estaduais-OSS', 'Estaduais-Outros', 'Estaduais-Universitarios',
       'Privado', 'ESTADUAL-AME'], dtype=object)

In [279]:
df['LEITOS_CLIN_ANTERIOR_A_COVID'] = df['LEITOS_CLIN_ANTERIOR_A_COVID'].apply(lambda x: int(x) if x > 0 else 0)
df['LEITOS_CLIN_ANTERIOR_A_COVID'].describe()

count    627.000000
mean      35.472089
std       45.015550
min        0.000000
25%        9.000000
50%       23.000000
75%       46.500000
max      456.000000
Name: LEITOS_CLIN_ANTERIOR_A_COVID, dtype: float64

In [280]:
df['LEITOS_CLIN_SUS'] = df['LEITOS_CLIN_SUS'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['LEITOS_CLIN_SUS'].unique()

array([  9,   0,  60,  18,  20,  15,  58,  82,  92,  55,  42,  40,  59,
        11, 100,  90,  10,  27,  12,  26,  70,  32,  46,  30,  13,  69,
        47,  51,  78,  33,   1,  50,  87,   3,  72,  43,  44,  31,  71,
        81,  57,  16,   5,  37,  65,   8,  67,  21,   2,  14, 110,  93,
       264,  17,  56,  86,  28,  35,  63,  48, 205, 190,  88, 336, 135,
         6,  53,  79,  38,  83, 143,  64,  62,  95,  49,  39,  19,  24,
        22,   4,  84,  54, 140,  52, 155,  36,  23,  29, 146,  25,  68,
       163,  45,  34,   7,  91, 105,  41, 132, 231, 111, 174,  74, 123,
        98])

In [281]:
df['LEITOS_CLIN_EXISTENTE_CONVERTIDO_PARA_COVID'] = df['LEITOS_CLIN_EXISTENTE_CONVERTIDO_PARA_COVID'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['LEITOS_CLIN_EXISTENTE_CONVERTIDO_PARA_COVID'].unique()

array([  0,  16,   3,  57,  35,   8,  40,  23,  10,  15,   4,   6,  26,
        28,  11,  24,  30,   2,  32,  64,   5,  34,  48,  60,  14,  19,
        12,  46,  38,  25,  80,  20,  78, 336,  22,  44,   7,   9,   1,
        29,  18,  31,  13,  50,  43,  55,  58,  17,  71, 103,  45,  21])

In [282]:
df['LEITO_CLINICO_AMPLIADO_EM_FUNCIONAMENTO'] = df['LEITO_CLINICO_AMPLIADO_EM_FUNCIONAMENTO'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['LEITO_CLINICO_AMPLIADO_EM_FUNCIONAMENTO'].unique()

array([  0,  20,   4,  70,   5,  22,  50,  30,  35,  11,  14, 160, 110,
        90,  81, 162,  12, 100,  36,  40,   6,  23,  27,  72,  10,   2,
        15,   8,  24,  18,  29,  16, 200, 294, 518, 240,  28,   7,  25,
        19,  56,  41,  26,  17,   3,  31,  42,  80,   1,  39, 177,   9,
        73])

In [283]:
df['LEITO_CLINICO_PARA_AMPLIACAO_FUTURA'] = df['LEITO_CLINICO_PARA_AMPLIACAO_FUTURA'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['LEITO_CLINICO_PARA_AMPLIACAO_FUTURA'].unique()

array([  0,  28,  30,  90,  26, 962, 148,  33,  31,  95,  11,  68,  25,
        94,  20,   2,  60,  37,  24,  22,   3,   4,  16,  40,   8,   5])

In [284]:
df['UTI_ADULTO_EXISTE'] = df['UTI_ADULTO_EXISTE'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_EXISTE'].unique()

array([  0,  10,   6,  12,  18,  19,   8,  11,  28,   4,  30,  59,   7,
         9,  40,  20, 119,   5,  13,  76,   1,  16,  85,  17,  37,  64,
        14,  72,  77,  26,  24, 128, 195,  21,  23,  63,  25, 120,  71,
        34,  35,  31,  29,   2,  36,  22,  52,  15, 117,  33])

In [285]:
df['UTI_ADULTO_SUS'] = df['UTI_ADULTO_SUS'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_SUS'].unique()

array([  0,  10,   6,  18,  19,   8,  11,  20,   4,  30,  59,   7,  40,
         9,  12, 119,  22,   2,  62,  16,  85,  17,  13,  14,  58,  74,
        15,  24, 128,  50,  21,  55,   5,  28,  31,   1,   3,  27,  26,
        52,  98,  25,  34])

In [286]:
df['UTI_ADULTO_EXISTENTE_CONVERTIDO_PARA_COVID'] = df['UTI_ADULTO_EXISTENTE_CONVERTIDO_PARA_COVID'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_EXISTENTE_CONVERTIDO_PARA_COVID'].unique()

array([  0,   1,  15,  10,   5,   2,  20,  27,  29,   3,  11,  12,   4,
        13,   8,   9,  19,  22,   6, 106,   7,  30,  16,  58])

In [287]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_1'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_1'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_1'].unique()

array([ 0, 23, 12, 20, 10,  9, 15, 30, 90, 11, 40,  5,  8,  3,  4,  2, 16,
        7, 13, 24, 18, 41,  1,  6])

In [288]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_2'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_2'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_2'].unique()

array([ 0, 26, 40, 10,  5,  4, 36,  6,  9, 46,  8, 15,  7, 17])

In [289]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_3'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_3'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_3'].unique()

array([ 0, 18, 10, 13, 20,  5,  8,  7, 11, 50, 56, 30, 25, 74, 60,  2,  9,
       19,  6,  1,  3])

In [290]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_4'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_4'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_4'].unique()

array([  0,  10,  16,  28,  70,   1,  40,  21,  30, 120,  20,   6,   4,
        22])

In [291]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_5'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_5'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_5'].unique()

array([ 0, 17, 30, 20, 10, 50,  2,  5,  9,  4])

In [292]:
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_6'] = df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_6'].apply(lambda x: 0 if x == '-' else x).apply(lambda x: int(x) if isinstance(x, str) else 0)
df['UTI_ADULTO_AMPLIACAO_HABIMEDIATA_REMESSA_6'].unique()

array([  0,   8,  12,  10,  18,  19,   9,  30, 165,  25, 188,  24,   2,
        16,   5,  80,  20,   6,  11,  14,  15,   3])

In [296]:
df.to_csv('./cleanHospitalMap.csv', sep=';', index=False)